void ioInit( void );
void boostConverterInit( void );
//void checkInputPower( void );
void updateTemperatureFilter( uint8_t moduloSeconds );
void serialPrintTemperature( void );
void adcInit( void );
void extInterruptInit( void );
//uint16_t getADC( uint8_t mux );
void updateBoostConverter(void);
void toggle_led( void );
void blip_led( void );
void copy_command( void );
void process_command( void );
void print_value( char *id, uint32_t value );
void print_csv( char *id, uint32_t value );
void uart_ok( void );
void process_uart( void );
void uartWelcome( void );
void uartInit( void );
void rtcInit( void );
void checkSerialIn( void );
void updateDateTime( void );
void serialPrintDateTime( void );
void serialPrintAcFrequency( void );
void readEepromToVars( void );
void updateVarsToEeprom( void );
//void checkNixieSleep( void );
void updateNixieOutputState( void );
void antiCathodePoisonPattern( uint16_t delay );
void checkCathodePoison( void );
void shiftRegisterPulse( void );
void shiftRegisterSetOutput( void );
void turnOnOffBoostConverter( uint8_t state );
uint8_t acPowerOk( void );
uint8_t dayOfWeek(uint8_t day, uint8_t month, uint16_t year);
void shiftByteOut( uint8_t byteToShift );
void sendIntegerToNixie( uint8_t intToSend, uint8_t doDecimal );
void nixiePrintTemperature( void );
void nixiePrintDate( void );
void nixiePrintTime( uint8_t doToggleDecimal );
void nixiePrintAcFrequency( void );
uint8_t isLeapYear( void );
void updateAcFrequency( void );
uint8_t inRange( uint32_t inputValue, uint32_t upperBound, uint32_t lowerBound );
int is_switch_pressed( char port, char pin, int ms_debounce, int ms_block );
uint32_t splitString( char aString[ 100 ] );
double readTemperature( void );